# Generated by Django 4.2.7 on 2024-02-27 09:49

from django.db import migrations, models
import django.db.models.deletion
import picture_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_image', models.ImageField(upload_to='styles_img/', verbose_name='style_image')),
                ('style_num', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Styles',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_image', models.ImageField(upload_to='img/', validators=[picture_upload.models.validate_is_picture, picture_upload.models.validate_max_size], verbose_name='contents_image')),
                ('created_image', models.ImageField(upload_to='created_img/', verbose_name='created_image')),
                ('style_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture_upload.styles')),
            ],
            options={
                'verbose_name_plural': 'UploadImage',
            },
        ),
    ]
