# Generated by Django 4.2.7 on 2023-12-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/', verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'picture_upload',
            },
        ),
    ]
