# Generated by Django 4.2.7 on 2023-12-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureupload',
            old_name='image',
            new_name='contents_image',
        ),
        migrations.AddField(
            model_name='pictureupload',
            name='style_image',
            field=models.ImageField(choices=[('cat', 'cat'), ('dog', 'dog')], default='cat', upload_to='img/'),
        ),
    ]
