# Generated by Django 4.2.7 on 2023-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_upload', '0002_rename_image_pictureupload_contents_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureupload',
            name='style_image',
            field=models.ImageField(choices=[('cat', '/Users/daiki/Desktop/style_transfer/style_transfer/static/img/cat.png'), ('dog', 'dog')], default='cat', upload_to='img/'),
        ),
    ]
