# Generated by Django 4.2.7 on 2023-12-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_upload', '0003_alter_pictureupload_style_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureupload',
            name='style_image',
            field=models.ImageField(choices=[('cat', None), ('dog', 'dog')], default='cat', upload_to='img/'),
        ),
    ]
