# Generated by Django 4.2.7 on 2023-12-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture_upload', '0004_alter_pictureupload_style_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_image', models.ImageField(upload_to='img/', verbose_name='style_image')),
                ('style_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_image', models.ImageField(upload_to='img/', verbose_name='contents_image')),
                ('style_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture_upload.styles')),
            ],
            options={
                'verbose_name_plural': 'UploadImage',
            },
        ),
        migrations.DeleteModel(
            name='PictureUpload',
        ),
    ]
