# Generated by Django 4.2.7 on 2023-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_upload', '0005_styles_uploadimage_delete_pictureupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='style_image',
            field=models.ImageField(upload_to='contents_img/', verbose_name='style_image'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='contents_image',
            field=models.ImageField(upload_to='style_img/', verbose_name='contents_image'),
        ),
    ]
