# Generated by Django 4.2.7 on 2023-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_upload', '0007_alter_styles_style_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='style_image',
            field=models.ImageField(upload_to='styles_img/', verbose_name='style_image'),
        ),
    ]
